#:schema = "https://json.schemastore.org/ruff.json"

line-length = 120

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["ANN001", "ANN101"]

[lint.per-file-ignores]
"tests/*" = ["S101"] # Ignore asserts in tests

[format]
quote-style = "single"
indent-style = "space"