
services:
  server:
    build:
      args:
        VERSION_TAG: ${VERSION_TAG:-latest}
      context: .
    container_name: time-tracker
    image: time-tracker:${VERSION_TAG:-latest}
    volumes:
      - c:/temp/time-tracker:/app/data
    ports:
      - 5000:5000
    environment:
      SQLALCHEMY_DATABASE_URI: sqlite:///data/time-tracker.db
      SECRET_KEY: this_is_my_secret_key_217149
      DAY_START_TIME: 08:30
      DAY_END_TIME: 17:00
    logging:
      driver: local
